name: Publish Python 🐍 distribution 📦 to PyPI

on:
  push:
    tags:
      - "v*"  # Trigger the workflow for any tag that starts with 'v'

jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12]  # Supports Python 3.10 to 3.12

    permissions:
      id-token: write  # Grant the workflow the ability to request the OIDC token

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build the package
      run: python -m build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      env:
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}  # If not using Trusted Publisher
